import { parseAsString, parseAsInteger, parseAsBoolean, parseAsFloat } from 'nuqs/server';
import { ItemMasterFilter } from '@/types/item-master';
import { ItemMasterFormData } from "@/validations/item-master";

export interface SelectOption {
  value: string;
  label: string;
  variant?: "default" | "secondary" | "destructive" | "outline";
  disabled?: boolean;
  shortName?: string;
}

// Status Options
export const statusOptions: SelectOption[] = [
  { label: "All Statuses", value: "" },
  { label: "Active", value: "true" },
  { label: "Inactive", value: "false" },
];

// Sort Options
export const sortOptions: SelectOption[] = [
  { value: "created_at", label: "Created Date" },
  { value: "updated_at", label: "Updated Date" },
  { value: "code", label: "Code" },
  { value: "name", label: "Name" },
  { value: "description", label: "Description" },
];

// Sort Order Options
export const sortOrderOptions: SelectOption[] = [
  { value: "desc", label: "Descending" },
  { value: "asc", label: "Ascending" }
];

// Page Size Options
export const pageSizeOptions: SelectOption[] = [
  { label: "10 per page", value: "10" },
  { label: "25 per page", value: "25" },
  { label: "50 per page", value: "50" },
  { label: "100 per page", value: "100" },
];

// nuqs Parsers
export const itemTypeParsers = {
  page: parseAsInteger.withDefault(1),
  pageSize: parseAsInteger.withDefault(10),
  sortBy: parseAsString.withDefault("created_at"),
  sortOrder: parseAsString.withDefault("desc") as any,
  search: parseAsString.withDefault(""),
  isActive: parseAsBoolean,
};

// Filter Default Values
export const defaultItemTypeFilter = {
  page: 1,
  pageSize: 10,
  sortBy: "created_at",
  sortOrder: "desc" as "asc" | "desc",
  search: "",
  isActive: undefined as boolean | undefined,
};

export const itemMasterFilterParsers = {
  search: parseAsString.withDefault(''),
  itemCode: parseAsString.withDefault(''),
  itemName: parseAsString.withDefault(''),
  shortName: parseAsString.withDefault(''),
  revNo: parseAsString.withDefault(''),
  itemTypeId: parseAsInteger.withDefault(0),
  subType: parseAsString.withDefault(''),
  gsInd: parseAsString.withDefault(''),
  goodsType: parseAsString.withDefault(''),
  pharmacopoeiaName: parseAsString.withDefault(''),
  unitOfMeasure: parseAsString.withDefault(''),
  issuingUnit: parseAsString.withDefault(''),
  hsn: parseAsString.withDefault(''),
  uqc: parseAsString.withDefault(''),
  drawingRef: parseAsString.withDefault(''),
  stdAssayStrength: parseAsString.withDefault(''),
  productType: parseAsString.withDefault(''),
  salesDivision: parseAsString.withDefault(''),
  productGroup: parseAsString.withDefault(''),
  vendorPartNo: parseAsString.withDefault(''),
  allergen: parseAsBoolean.withDefault(false),
  activeIngredient: parseAsString.withDefault(''),
  packingFreightInsuranceServices: parseAsBoolean.withDefault(false),
  boughtOut: parseAsBoolean.withDefault(false),
  jobWork: parseAsBoolean.withDefault(false),
  imported: parseAsBoolean.withDefault(false),
  taxCreditApplicable: parseAsBoolean.withDefault(false),
  manufactured: parseAsBoolean.withDefault(false),
  sold: parseAsBoolean.withDefault(false),
  keyProduct: parseAsBoolean.withDefault(false),
  exported: parseAsBoolean.withDefault(false),
  batchNotApplicable: parseAsBoolean.withDefault(false),
  qcRequired: parseAsBoolean.withDefault(false),
  mfgDateApplicable: parseAsBoolean.withDefault(false),
  expiryDateApplicable: parseAsBoolean.withDefault(false),
  trackSerialNos: parseAsBoolean.withDefault(false),
  mfgLocNameRequired: parseAsBoolean.withDefault(false),
  mfgMmYyyyApplicable: parseAsBoolean.withDefault(false),
  expiryMmYyyyApplicable: parseAsBoolean.withDefault(false),
  principalForStatutoryReporting: parseAsBoolean.withDefault(false),
  minUomIssConvFactor: parseAsFloat.withDefault(0),
  maxUomIssConvFactor: parseAsFloat.withDefault(0),
  minUomUqcConvFactor: parseAsFloat.withDefault(0),
  maxUomUqcConvFactor: parseAsFloat.withDefault(0),
  minShelfLifeMonths: parseAsInteger.withDefault(0),
  maxShelfLifeMonths: parseAsInteger.withDefault(0),
  minShelfLifeDays: parseAsInteger.withDefault(0),
  maxShelfLifeDays: parseAsInteger.withDefault(0),
  minStdRate: parseAsFloat.withDefault(0),
  maxStdRate: parseAsFloat.withDefault(0),
  minLeadTimeDays: parseAsInteger.withDefault(0),
  maxLeadTimeDays: parseAsInteger.withDefault(0),
  minStdLossOnDry: parseAsFloat.withDefault(0),
  maxStdLossOnDry: parseAsFloat.withDefault(0),
  minSafetyStock: parseAsFloat.withDefault(0),
  maxSafetyStock: parseAsFloat.withDefault(0),
  minEconomicOrderQty: parseAsFloat.withDefault(0),
  maxEconomicOrderQty: parseAsFloat.withDefault(0),
  minDesiredPackSize: parseAsFloat.withDefault(0),
  maxDesiredPackSize: parseAsFloat.withDefault(0),
  minAllowedAllergenPercent: parseAsFloat.withDefault(0),
  maxAllowedAllergenPercent: parseAsFloat.withDefault(0),
  minStdMfgFeesPerUnit: parseAsFloat.withDefault(0),
  maxStdMfgFeesPerUnit: parseAsFloat.withDefault(0),
  minConversionFactor: parseAsFloat.withDefault(0),
  maxConversionFactor: parseAsFloat.withDefault(0),
  createdFrom: parseAsString.withDefault(''),
  createdTo: parseAsString.withDefault(''),
  updatedFrom: parseAsString.withDefault(''),
  updatedTo: parseAsString.withDefault(''),
  sortBy: parseAsString.withDefault('itemName'),
  sortDescending: parseAsBoolean.withDefault(false),
  pageNumber: parseAsInteger.withDefault(1),
  pageSize: parseAsInteger.withDefault(20),
  currentBuyer: parseAsString.withDefault(''),
  mainProdCentre: parseAsString.withDefault(''),
  freightOn: parseAsString.withDefault(''),
};

export const getItemMasterDefaultValues = (): ItemMasterFormData => ({
  revNo: "",
  itemTypeId: 0,
  subType: "",
  gsInd: "",
  goodsType: "",
  itemName: "",
  shortName: "",
  pharmacopoeiaName: "",
  unitOfMeasure: "",
  issuingUnit: "",
  hsn: "",
  uqc: "",
  uomIssConvFactor: undefined,
  uomUqcConvFactor: undefined,
  drawingRef: "",
  currentBuyer: "",
  economicOrderQty: undefined,
  desiredPackSize: undefined,
  freightOn: "",
  stdAssayStrength: undefined,
  shelfLifeMonths: undefined,
  shelfLifeDays: undefined,
  stdRate: undefined,
  stdLossOnDry: undefined,
  safetyStock: undefined,
  allowedAllergenPercent: undefined,
  stdMfgFeesPerUnit: undefined,
  mainProdCentre: "",
  sold: false,
  keyProduct: false,
  exported: false,
  productType: "",
  salesDivision: "",
  productGroup: "",
  conversionFactor: undefined,
  vendorPartNo: "",
  boughtOut: false,
  jobWork: false,
  imported: false,
  taxCreditApplicable: false,
  manufactured: false,
  batchNotApplicable: false,
  qcRequired: false,
  allergen: false,
  mfgDateApplicable: false,
  expiryDateApplicable: false,
  trackSerialNos: false,
  packingFreightInsuranceServices: false,
  activeIngredient: false,
  mfgLocNameRequired: false,
  mfgMmYyyyApplicable: false,
  expiryMmYyyyApplicable: false,
  principalForStatutoryReporting: false,
  // Sales Details
  packSizeApplicable: false,
  defaultPackSize: "",
   saleableUnitContains: undefined,
  qtyPerBox: undefined,
  boxesPerCase: undefined,
  casePackingType: "",
  packingRate: undefined,
  qtyPerCase: undefined,
  netWeightCase: undefined,
  tareWeightCase: undefined,
  grossWeightCase: undefined,
  grossWeightUnit: undefined,
  caseDimensionsInches: "",
  caseVolumeCft: undefined,
  caseDimensionsCm: "",
  caseVolumeCbm: undefined,
  minSaleRate: undefined,
  minSoQty: undefined,
  tertiaryGtin: "",
  secondaryGtin: "",
  primaryGtin: "",
  minBatchQtyAutoloading: undefined,
  considerAsNewProductTill: "",
  interfaceCode: "",
  specs: "",
  // Bought Out Details
  purchaseBasedOn: "",
  excessPlanningPercent: undefined,
  boughtOutReorderLevel: undefined,
  minStockLevel: undefined,
  maxStockLevel: undefined,
  minBalanceShelfLifeDays: undefined,
  customDutyPercent: undefined,
  igstPercent: undefined,
  swsPercent: undefined,
  maxPurchaseRate: undefined,
  stopProcurement: false,
  // Stock Analysis
  abcConsumptionValue: "",
  xyzStockValue: "",
  fsnMovement: "",
  vedAnalysis: "",
  // Export Details
  itemDescriptionForExports: "",
  exportProductGroupCode: "",
  exportProductGroupName: "",
  depbRateListSrlNo: "",
  depbRate: undefined,
  depbValueCap: undefined,
  depbRemarks: "",
      dutyDrawbackSrlNo: "",
    dutyDrawbackRateType: "",
    dutyDrawbackRate: undefined,
    dutyDrawbackValueCap: undefined,
    dutyDrawbackRemarks: "",
  // Specifications
  itemSpecification: "",
  substituteItemFor: "",
  customTariffNo: "",
  exciseTariffNo: "",
  vatCommCode: "",
  convFactor: undefined,
  oldCode: "",
  standardWeight: undefined,
  standardConversionCostFactor: undefined,
  standardPackingCostFactor: undefined,
  costFactorPercent: undefined,
  packingCostRs: undefined,
  // Other Details
  packShort: "",
  productCast: "",
  pvcColor: "",
  color: "",
  flavour: "",
  fragrance: "",
  form: "",
  packagingStyle: "",
  changePart: "",
  size: "",
  withLeaflet: false,
  withApplicator: false,
  withWad: false,
  withSilica: false,
  withCotton: false,
  withMeasuringCap: false,
  withSpoon: false,
  packingNp: "",
  packingNpQty: "",
  packingStylePtd: "",
  packingStylePtdQty: "",
  notePerStrip: "",
  packShortPtdSpec: "",
  packShortPtdSize: "",
  packShortPtdQty: "",
  packingStyleNpSize: "",
  packingStyleNpQty: "",
  noteForCtn: "",
  outerSize: "",
  outerQty: "",
  shrink: "",
  shrinkPacking: "",
  shipperSize: "",
  qtyPerShipper: "",
  shipperNote: "",
});

export const mapItemToFormData = (item: any): ItemMasterFormData => {
  if (!item) return getItemMasterDefaultValues();

  return {
    revNo: item.revNo || "",
    itemTypeId: item.itemTypeId || 0,
    subType: item.subType || "",
    gsInd: item.gsInd || "",
    goodsType: item.goodsType || "",
    itemName: item.itemName || "",
    shortName: item.shortName || "",
    pharmacopoeiaName: item.pharmacopoeiaName || "",
    unitOfMeasure: item.unitOfMeasure || "",
    issuingUnit: item.issuingUnit || "",
    hsn: item.hsn || "",
    uqc: item.uqc || "",
    uomIssConvFactor: item.uomIssConvFactor ? item.uomIssConvFactor.toString() : undefined,
    uomUqcConvFactor: item.uomUqcConvFactor ? item.uomUqcConvFactor.toString() : undefined,
    drawingRef: item.drawingRef || "",
    currentBuyer: item.currentBuyer || "",
    economicOrderQty: item.economicOrderQty ? item.economicOrderQty.toString() : undefined,
    desiredPackSize: item.desiredPackSize ? item.desiredPackSize.toString() : undefined,
    freightOn: item.freightOn || "",
    stdAssayStrength: item.stdAssayStrength ? item.stdAssayStrength.toString() : undefined,
    shelfLifeMonths: item.shelfLifeMonths ? item.shelfLifeMonths.toString() : undefined,
    shelfLifeDays: item.shelfLifeDays ? item.shelfLifeDays.toString() : undefined,
    stdRate: item.stdRate ? item.stdRate.toString() : undefined,
    stdLossOnDry: item.stdLossOnDry ? item.stdLossOnDry.toString() : undefined,
    safetyStock: item.safetyStock ? item.safetyStock.toString() : undefined,
    allowedAllergenPercent: item.allowedAllergenPercent ? item.allowedAllergenPercent.toString() : undefined,
    stdMfgFeesPerUnit: item.stdMfgFeesPerUnit ? item.stdMfgFeesPerUnit.toString() : undefined,
    mainProdCentre: item.mainProdCentre || "",
    sold: item.sold || false,
    keyProduct: item.keyProduct || false,
    exported: item.exported || false,
    productType: item.productType || "",
    salesDivision: item.salesDivision || "",
    productGroup: item.productGroup || "",
    conversionFactor: item.conversionFactor ? item.conversionFactor.toString() : undefined,
    vendorPartNo: item.vendorPartNo || "",
    boughtOut: item.boughtOut || false,
    jobWork: item.jobWork || false,
    imported: item.imported || false,
    taxCreditApplicable: item.taxCreditApplicable || false,
    manufactured: item.manufactured || false,
    batchNotApplicable: item.batchNotApplicable || false,
    qcRequired: item.qcRequired || false,
    allergen: item.allergen || false,
    mfgDateApplicable: item.mfgDateApplicable || false,
    expiryDateApplicable: item.expiryDateApplicable || false,
    trackSerialNos: item.trackSerialNos || false,
    packingFreightInsuranceServices: item.packingFreightInsuranceServices || false,
    activeIngredient: item.activeIngredient || false,
    mfgLocNameRequired: item.mfgLocNameRequired || false,
    mfgMmYyyyApplicable: item.mfgMmYyyyApplicable || false,
    expiryMmYyyyApplicable: item.expiryMmYyyyApplicable || false,
    principalForStatutoryReporting: item.principalForStatutoryReporting || false,
    // Map sales details data - handle string values from backend
    packSizeApplicable: item.salesDetail?.packSizeApplicable || false,
    defaultPackSize: item.salesDetail?.defaultPackSize || "",
    saleableUnitContains: item.salesDetail?.saleableUnitContains ? item.salesDetail.saleableUnitContains.toString() : undefined,
    qtyPerBox: item.salesDetail?.qtyPerBox ? item.salesDetail.qtyPerBox.toString() : undefined,
    boxesPerCase: item.salesDetail?.boxesPerCase ? item.salesDetail.boxesPerCase.toString() : undefined,
    casePackingType: item.salesDetail?.casePackingType || "",
    packingRate: item.salesDetail?.packingRate ? item.salesDetail.packingRate.toString() : undefined,
    qtyPerCase: item.salesDetail?.qtyPerCase ? item.salesDetail.qtyPerCase.toString() : undefined,
    netWeightCase: item.salesDetail?.netWeightCase ? item.salesDetail.netWeightCase.toString() : undefined,
    tareWeightCase: item.salesDetail?.tareWeightCase ? item.salesDetail.tareWeightCase.toString() : undefined,
    grossWeightCase: item.salesDetail?.grossWeightCase ? item.salesDetail.grossWeightCase.toString() : undefined,
    grossWeightUnit: item.salesDetail?.grossWeightUnit ? item.salesDetail.grossWeightUnit.toString() : undefined,
    caseDimensionsInches: item.salesDetail?.caseDimensionsInches || "",
    caseVolumeCft: item.salesDetail?.caseVolumeCft ? item.salesDetail.caseVolumeCft.toString() : undefined,
    caseDimensionsCm: item.salesDetail?.caseDimensionsCm || "",
    caseVolumeCbm: item.salesDetail?.caseVolumeCbm ? item.salesDetail.caseVolumeCbm.toString() : undefined,
    minSaleRate: item.salesDetail?.minSaleRate ? item.salesDetail.minSaleRate.toString() : undefined,
    minSoQty: item.salesDetail?.minSoQty ? item.salesDetail.minSoQty.toString() : undefined,
    tertiaryGtin: item.salesDetail?.tertiaryGtin || "",
    secondaryGtin: item.salesDetail?.secondaryGtin || "",
    primaryGtin: item.salesDetail?.primaryGtin || "",
    minBatchQtyAutoloading: item.salesDetail?.minBatchQtyAutoloading ? item.salesDetail.minBatchQtyAutoloading.toString() : undefined,
    considerAsNewProductTill: item.salesDetail?.considerAsNewProductTill || "",
    interfaceCode: item.salesDetail?.interfaceCode || "",
    specs: item.salesDetail?.specs || "",
    // Map specification data
    itemSpecification: item.specification?.specification || "",
    substituteItemFor: item.specification?.substituteForItemCode || "",
    customTariffNo: item.specification?.customTariffNo || "",
    exciseTariffNo: item.specification?.exciseTariffNo || "",
    vatCommCode: item.specification?.vatCommCode || "",
    convFactor: item.specification?.conversionFactor ? item.specification.conversionFactor.toString() : "",
    oldCode: item.specification?.oldCode || "",
    standardWeight: item.specification?.standardWeight ? item.specification.standardWeight.toString() : "",
    standardConversionCostFactor: item.specification?.standardConversionCostFactor ? item.specification.standardConversionCostFactor.toString() : "",
    standardPackingCostFactor: item.specification?.standardPackingCostFactor ? item.specification.standardPackingCostFactor.toString() : "",
    costFactorPercent: item.specification?.costFactorPercent ? item.specification.costFactorPercent.toString() : "",
    packingCostRs: item.specification?.packingCostRs ? item.specification.packingCostRs.toString() : "",
    // Map bought out details data
    purchaseBasedOn: item.boughtOutDetails?.purchaseBasedOn || "",
    excessPlanningPercent: item.boughtOutDetails?.excessPlanningPercent ? item.boughtOutDetails.excessPlanningPercent.toString() : undefined,
    boughtOutReorderLevel: item.boughtOutDetails?.reorderLevel ? item.boughtOutDetails.reorderLevel.toString() : undefined,
    minStockLevel: item.boughtOutDetails?.minStockLevel ? item.boughtOutDetails.minStockLevel.toString() : undefined,
    maxStockLevel: item.boughtOutDetails?.maxStockLevel ? item.boughtOutDetails.maxStockLevel.toString() : undefined,
    minBalanceShelfLifeDays: item.boughtOutDetails?.minBalanceShelfLifeDays ? item.boughtOutDetails.minBalanceShelfLifeDays.toString() : undefined,
    customDutyPercent: item.boughtOutDetails?.customDutyPercent ? item.boughtOutDetails.customDutyPercent.toString() : undefined,
    igstPercent: item.boughtOutDetails?.igstPercent ? item.boughtOutDetails.igstPercent.toString() : undefined,
    swsPercent: item.boughtOutDetails?.swsPercent ? item.boughtOutDetails.swsPercent.toString() : undefined,
    maxPurchaseRate: item.boughtOutDetails?.maxPurchaseRate ? item.boughtOutDetails.maxPurchaseRate.toString() : undefined,
    stopProcurement: item.boughtOutDetails?.stopProcurement || false,
    // Map stock analysis data
    abcConsumptionValue: item.stockAnalysis?.abcConsumptionValue || "",
    xyzStockValue: item.stockAnalysis?.xyzStockValue || "",
    fsnMovement: item.stockAnalysis?.fsnMovement || "",
    vedAnalysis: item.stockAnalysis?.vedAnalysis || "",
    itemDescriptionForExports: item.exportDetails?.itemDescriptionForExports || "",
    exportProductGroupCode: item.exportDetails?.exportProductGroupCode || "",
    exportProductGroupName: item.exportDetails?.exportProductGroupName || "",
    depbRateListSrlNo: item.exportDetails?.depbRateListSrlNo || "",
    depbRate: item.exportDetails?.depbRate ? item.exportDetails.depbRate.toString() : "",
    depbValueCap: item.exportDetails?.depbValueCap ? item.exportDetails.depbValueCap.toString() : "",
    depbRemarks: item.exportDetails?.depbRemarks || "",
    dutyDrawbackSrlNo: item.exportDetails?.dutyDrawbackSrlNo || "",
    dutyDrawbackRateType: item.exportDetails?.dutyDrawbackRateType || "",
    dutyDrawbackRate: item.exportDetails?.dutyDrawbackRate ? item.exportDetails.dutyDrawbackRate.toString() : "",
    dutyDrawbackValueCap: item.exportDetails?.dutyDrawbackValueCap ? item.exportDetails.dutyDrawbackValueCap.toString() : "",
    dutyDrawbackRemarks: item.exportDetails?.dutyDrawbackRemarks || "",
    // Map other details data
    packShort: item.otherDetails?.packShort || "",
    productCast: item.otherDetails?.productCast || "",
    pvcColor: item.otherDetails?.pvcColor || "",
    color: item.otherDetails?.color || "",
    flavour: item.otherDetails?.flavour || "",
    fragrance: item.otherDetails?.fragrance || "",
    form: item.otherDetails?.form || "",
    packagingStyle: item.otherDetails?.packagingStyle || "",
    changePart: item.otherDetails?.changePart || "",
    size: item.otherDetails?.size || "",
    withLeaflet: item.otherDetails?.withLeaflet || false,
    withApplicator: item.otherDetails?.withApplicator || false,
    withWad: item.otherDetails?.withWad || false,
    withSilica: item.otherDetails?.withSilica || false,
    withCotton: item.otherDetails?.withCotton || false,
    withMeasuringCap: item.otherDetails?.withMeasuringCap || false,
    withSpoon: item.otherDetails?.withSpoon || false,
    packingNp: item.otherDetails?.packingNp || "",
    packingNpQty: item.otherDetails?.packingNpQty ? item.otherDetails.packingNpQty.toString() : "",
    packingStylePtd: item.otherDetails?.packingStylePtd || "",
    packingStylePtdQty: item.otherDetails?.packingStylePtdQty ? item.otherDetails.packingStylePtdQty.toString() : "",
    notePerStrip: item.otherDetails?.notePerStrip || "",
    packShortPtdSpec: item.otherDetails?.packShortPtdSpec || "",
    packShortPtdSize: item.otherDetails?.packShortPtdSize || "",
    packShortPtdQty: item.otherDetails?.packShortPtdQty ? item.otherDetails.packShortPtdQty.toString() : "",
    packingStyleNpSize: item.otherDetails?.packingStyleNpSize || "",
    packingStyleNpQty: item.otherDetails?.packingStyleNpQty ? item.otherDetails.packingStyleNpQty.toString() : "",
    noteForCtn: item.otherDetails?.noteForCtn || "",
    outerSize: item.otherDetails?.outerSize || "",
    outerQty: item.otherDetails?.outerQty ? item.otherDetails.outerQty.toString() : "",
    shrink: item.otherDetails?.shrink || "",
    shrinkPacking: item.otherDetails?.shrinkPacking || "",
    shipperSize: item.otherDetails?.shipperSize || "",
    qtyPerShipper: item.otherDetails?.qtyPerShipper ? item.otherDetails.qtyPerShipper.toString() : "",
    shipperNote: item.otherDetails?.shipperNote || "",
  };
};

// Helper function to convert numeric values to strings for validation
const convertNumericToString = (value: any): string | undefined => {
  if (value === null || value === undefined || value === "") return undefined;
  return value.toString();
};

// Helper function to convert numeric values to strings for API (returns empty string for null/undefined)
const convertNumericToStringForApi = (value: any): string => {
  if (value === null || value === undefined || value === "") return "";
  return value.toString();
};

export const transformFormDataToApi = (data: ItemMasterFormData) => {
  // Convert numeric values to strings for validation
  const convertedData = {
    ...data,
    uomIssConvFactor: convertNumericToString(data.uomIssConvFactor),
    uomUqcConvFactor: convertNumericToString(data.uomUqcConvFactor),
    economicOrderQty: convertNumericToString(data.economicOrderQty),
    desiredPackSize: convertNumericToString(data.desiredPackSize),
    stdAssayStrength: convertNumericToString(data.stdAssayStrength),
    shelfLifeMonths: convertNumericToString(data.shelfLifeMonths),
    shelfLifeDays: convertNumericToString(data.shelfLifeDays),
    stdRate: convertNumericToString(data.stdRate),
    stdLossOnDry: convertNumericToString(data.stdLossOnDry),
    safetyStock: convertNumericToString(data.safetyStock),
    allowedAllergenPercent: convertNumericToString(data.allowedAllergenPercent),
    stdMfgFeesPerUnit: convertNumericToString(data.stdMfgFeesPerUnit),
    conversionFactor: convertNumericToString(data.conversionFactor),
    saleableUnitContains: convertNumericToString(data.saleableUnitContains),
    qtyPerBox: convertNumericToString(data.qtyPerBox),
    boxesPerCase: convertNumericToString(data.boxesPerCase),
    packingRate: convertNumericToString(data.packingRate),
    qtyPerCase: convertNumericToString(data.qtyPerCase),
    netWeightCase: convertNumericToString(data.netWeightCase),
    tareWeightCase: convertNumericToString(data.tareWeightCase),
    grossWeightCase: convertNumericToString(data.grossWeightCase),
    grossWeightUnit: convertNumericToString(data.grossWeightUnit),
    caseVolumeCft: convertNumericToString(data.caseVolumeCft),
    caseVolumeCbm: convertNumericToString(data.caseVolumeCbm),
    minSaleRate: convertNumericToString(data.minSaleRate),
    minSoQty: convertNumericToString(data.minSoQty),
    minBatchQtyAutoloading: convertNumericToString(data.minBatchQtyAutoloading),
    excessPlanningPercent: convertNumericToString(data.excessPlanningPercent),
    boughtOutReorderLevel: convertNumericToString(data.boughtOutReorderLevel),
    minStockLevel: convertNumericToString(data.minStockLevel),
    maxStockLevel: convertNumericToString(data.maxStockLevel),
    minBalanceShelfLifeDays: convertNumericToString(data.minBalanceShelfLifeDays),
    customDutyPercent: convertNumericToString(data.customDutyPercent),
    igstPercent: convertNumericToString(data.igstPercent),
    swsPercent: convertNumericToString(data.swsPercent),
    maxPurchaseRate: convertNumericToString(data.maxPurchaseRate),
    convFactor: convertNumericToString(data.convFactor),
    standardWeight: convertNumericToString(data.standardWeight),
    standardConversionCostFactor: convertNumericToString(data.standardConversionCostFactor),
    standardPackingCostFactor: convertNumericToString(data.standardPackingCostFactor),
    costFactorPercent: convertNumericToString(data.costFactorPercent),
    packingCostRs: convertNumericToString(data.packingCostRs),
    depbRate: convertNumericToString(data.depbRate),
    depbValueCap: convertNumericToString(data.depbValueCap),
    dutyDrawbackRate: convertNumericToString(data.dutyDrawbackRate),
    dutyDrawbackValueCap: convertNumericToString(data.dutyDrawbackValueCap),
    packingNpQty: convertNumericToString(data.packingNpQty),
    packingStylePtdQty: convertNumericToString(data.packingStylePtdQty),
    packShortPtdQty: convertNumericToString(data.packShortPtdQty),
    packingStyleNpQty: convertNumericToString(data.packingStyleNpQty),
    outerQty: convertNumericToString(data.outerQty),
    qtyPerShipper: convertNumericToString(data.qtyPerShipper),
  };

  // Remove nested form fields from the main item data
  const {
    itemSpecification,
    substituteItemFor,
    customTariffNo,
    exciseTariffNo,
    vatCommCode,
    convFactor,
    oldCode,
    standardWeight,
    standardConversionCostFactor,
    standardPackingCostFactor,
    costFactorPercent,
    packingCostRs,
    purchaseBasedOn,
    excessPlanningPercent,
    boughtOutReorderLevel,
    minStockLevel,
    maxStockLevel,
    minBalanceShelfLifeDays,
    customDutyPercent,
    igstPercent,
    swsPercent,
    maxPurchaseRate,
    stopProcurement,
    abcConsumptionValue,
    xyzStockValue,
    fsnMovement,
    vedAnalysis,
    itemDescriptionForExports,
    exportProductGroupCode,
    exportProductGroupName,
    depbRateListSrlNo,
    depbRate,
    depbValueCap,
    depbRemarks,
    dutyDrawbackSrlNo,
    dutyDrawbackRateType,
    dutyDrawbackRate,
    dutyDrawbackValueCap,
    dutyDrawbackRemarks,
    packSizeApplicable,
    defaultPackSize,
    saleableUnitContains,
    qtyPerBox,
    boxesPerCase,
    casePackingType,
    packingRate,
    qtyPerCase,
    netWeightCase,
    tareWeightCase,
    grossWeightCase,
    grossWeightUnit,
    caseDimensionsInches,
    caseVolumeCft,
    caseDimensionsCm,
    caseVolumeCbm,
    minSaleRate,
    minSoQty,
    tertiaryGtin,
    secondaryGtin,
    primaryGtin,
    minBatchQtyAutoloading,
    considerAsNewProductTill,
    interfaceCode,
    specs,

    packShort,
    productCast,
    pvcColor,
    color,
    flavour,
    fragrance,
    form,
    packagingStyle,
    changePart,
    size,
    withLeaflet,
    withApplicator,
    withWad,
    withSilica,
    withCotton,
    withMeasuringCap,
    withSpoon,
    packingNp,
    packingNpQty,
    packingStylePtd,
    packingStylePtdQty,
    notePerStrip,
    packShortPtdSpec,
    packShortPtdSize,
    packShortPtdQty,
    packingStyleNpSize,
    packingStyleNpQty,
    noteForCtn,
    outerSize,
    outerQty,
    shrink,
    shrinkPacking,
    shipperSize,
    qtyPerShipper,
    shipperNote,
    ...itemData
  } = convertedData;

  return {
    ...itemData,
    // Include sales details data if any fields are filled
    salesDetail: (packSizeApplicable !== undefined || defaultPackSize || saleableUnitContains || qtyPerBox || boxesPerCase || casePackingType || packingRate || qtyPerCase || netWeightCase || tareWeightCase || grossWeightCase || grossWeightUnit || caseDimensionsInches || caseVolumeCft || caseDimensionsCm || caseVolumeCbm || minSaleRate || minSoQty || tertiaryGtin || secondaryGtin || primaryGtin || minBatchQtyAutoloading || considerAsNewProductTill || interfaceCode || specs) ? {
      itemId: itemData.itemTypeId || 0,
      packSizeApplicable: packSizeApplicable || false,
      defaultPackSize,
      saleableUnitContains: saleableUnitContains ? saleableUnitContains.toString() : undefined,
      qtyPerBox: qtyPerBox ? qtyPerBox.toString() : undefined,
      boxesPerCase: boxesPerCase ? boxesPerCase.toString() : undefined,
      casePackingType,
      packingRate: packingRate ? packingRate.toString() : undefined,
      qtyPerCase: qtyPerCase ? qtyPerCase.toString() : undefined,
      netWeightCase: netWeightCase ? netWeightCase.toString() : undefined,
      tareWeightCase: tareWeightCase ? tareWeightCase.toString() : undefined,
      grossWeightCase: grossWeightCase ? grossWeightCase.toString() : undefined,
      grossWeightUnit: grossWeightUnit ? grossWeightUnit.toString() : undefined,
      caseDimensionsInches,
      caseVolumeCft: caseVolumeCft ? caseVolumeCft.toString() : undefined,
      caseDimensionsCm,
      caseVolumeCbm: caseVolumeCbm ? caseVolumeCbm.toString() : undefined,
      minSaleRate: minSaleRate ? minSaleRate.toString() : undefined,
      minSoQty: minSoQty ? minSoQty.toString() : undefined,
      tertiaryGtin,
      secondaryGtin,
      primaryGtin,
      minBatchQtyAutoloading: minBatchQtyAutoloading ? minBatchQtyAutoloading.toString() : undefined,
      considerAsNewProductTill,
      interfaceCode,
      specs,
    } : undefined,
    // Include specification data if any fields are filled
    specification: (itemSpecification || substituteItemFor || customTariffNo || exciseTariffNo || vatCommCode || convFactor || oldCode || standardWeight || standardConversionCostFactor || standardPackingCostFactor || costFactorPercent || packingCostRs) ? {
      specification: itemSpecification,
        SubstituteForItemCode: substituteItemFor || "N/A",
        CustomTariffNo: customTariffNo || "",
        ExciseTariffNo: exciseTariffNo || "",
        VatCommCode: vatCommCode || "",
      conversionFactor: convFactor || "",
              OldCode: oldCode || "",
        StandardWeight: standardWeight || "",
        StandardConversionCostFactor: standardConversionCostFactor || "",
        StandardPackingCostFactor: standardPackingCostFactor || "",
      costFactorPercent: costFactorPercent || "",
      packingCostRs: packingCostRs || "",
    } : undefined,
    // Include bought out details data if any fields are filled
    boughtOutDetails: (purchaseBasedOn || excessPlanningPercent || boughtOutReorderLevel || minStockLevel || maxStockLevel || minBalanceShelfLifeDays || customDutyPercent || igstPercent || swsPercent || maxPurchaseRate || stopProcurement) ? {
      purchaseBasedOn,
      excessPlanningPercent: excessPlanningPercent ? excessPlanningPercent.toString() : undefined,
      reorderLevel: boughtOutReorderLevel ? boughtOutReorderLevel.toString() : undefined,
      minStockLevel: minStockLevel ? minStockLevel.toString() : undefined,
      maxStockLevel: maxStockLevel ? maxStockLevel.toString() : undefined,
      minBalanceShelfLifeDays: minBalanceShelfLifeDays ? minBalanceShelfLifeDays.toString() : undefined,
      customDutyPercent: customDutyPercent ? customDutyPercent.toString() : undefined,
      igstPercent: igstPercent ? igstPercent.toString() : undefined,
      swsPercent: swsPercent ? swsPercent.toString() : undefined,
      maxPurchaseRate: maxPurchaseRate ? maxPurchaseRate.toString() : undefined,
      stopProcurement,
    } : undefined,
    // Include stock analysis data if any fields are filled
    stockAnalysis: (abcConsumptionValue || xyzStockValue || fsnMovement || vedAnalysis) ? {
      itemId: itemData.itemTypeId || 0,
      abcConsumptionValue,
      xyzStockValue,
      fsnMovement,
      vedAnalysis,
    } : undefined,
    // Include export details data if any fields are filled
    exportDetails: (itemDescriptionForExports || exportProductGroupCode || exportProductGroupName || depbRateListSrlNo || depbRate || depbValueCap || depbRemarks || dutyDrawbackSrlNo  || dutyDrawbackRateType || dutyDrawbackValueCap || dutyDrawbackRemarks) ? {
      itemId: itemData.itemTypeId || 0,
      itemDescriptionForExports,
      ExportProductGroupCode: exportProductGroupCode,
      ExportProductGroupName: exportProductGroupName,
      DepbRateListSrlNo: depbRateListSrlNo,
      DepbRate: depbRate || "",
      DepbValueCap: depbValueCap || "",
      DepbRemarks: depbRemarks || "",
      DutyDrawbackSrlNo: dutyDrawbackSrlNo || "",
      DutyDrawbackRateType: dutyDrawbackRateType || "",
      DutyDrawbackRate: dutyDrawbackRate || "",
      DutyDrawbackValueCap: dutyDrawbackValueCap || "",
      DutyDrawbackRemarks: dutyDrawbackRemarks || "",
    } : undefined,
    // Include other details data if any fields are filled
    otherDetails: (packShort || productCast || pvcColor || color || flavour || fragrance || form || packagingStyle || changePart || size || withLeaflet || withApplicator || withWad || withSilica || withCotton || withMeasuringCap || withSpoon || packingNp || packingNpQty || packingStylePtd || packingStylePtdQty || notePerStrip || packShortPtdSpec || packShortPtdSize || packShortPtdQty || packingStyleNpSize || packingStyleNpQty || noteForCtn || outerSize || outerQty || shrink || shrinkPacking || shipperSize || qtyPerShipper || shipperNote) ? {
      itemId: itemData.itemTypeId || 0,
      packShort,
      productCast,
      pvcColor,
      color,
      flavour,
      fragrance,
      form,
      packagingStyle,
      changePart,
      size,
      withLeaflet: withLeaflet || false,
      withApplicator: withApplicator || false,
      withWad: withWad || false,
      withSilica: withSilica || false,
      withCotton: withCotton || false,
      withMeasuringCap: withMeasuringCap || false,
      withSpoon: withSpoon || false,
      packingNp,
      packingNpQty: packingNpQty || "",
      packingStylePtd: packingStylePtd || "",
      packingStylePtdQty: packingStylePtdQty || "",
      notePerStrip: notePerStrip || "",
      packShortPtdSpec: packShortPtdSpec || "",
      packShortPtdSize: packShortPtdSize || "",
      packShortPtdQty: packShortPtdQty || "",
      packingStyleNpSize: packingStyleNpSize || "",
      packingStyleNpQty: packingStyleNpQty || "",
      noteForCtn: noteForCtn || "",
      outerSize: outerSize || "",
      outerQty: outerQty || "",
      shrink: shrink || "",
      shrinkPacking: shrinkPacking || "",
      shipperSize: shipperSize || "",
      qtyPerShipper: qtyPerShipper || "",
      shipperNote: shipperNote || "",
    } : undefined,
  };
};

export const clearItemMasterFilters = () => {
  return {
    search: '',
    itemCode: '',
    itemName: '',
    shortName: '',
    revNo: '',
    itemTypeId: null,
    subType: '',
    gsInd: '',
    goodsType: '',
    pharmacopoeiaName: '',
    unitOfMeasure: '',
    issuingUnit: '',
    drawingRef: '',
    stdAssayStrength: null,
    productType: '',
    salesDivision: '',
    productGroup: '',
    vendorPartNo: '',
    allergen: '',
    activeIngredient: '',
    packingFreightInsuranceServices: '',
    boughtOut: null,
    jobWork: null,
    imported: null,
    taxCreditApplicable: null,
    manufactured: null,
    sold: null,
    keyProduct: null,
    exported: null,
    batchNotApplicable: null,
    qcRequired: null,
    mfgDateApplicable: null,
    expiryDateApplicable: null,
    trackSerialNos: null,
    mfgLocNameRequired: null,
    mfgMmYyyyApplicable: null,
    expiryMmYyyyApplicable: null,
    principalForStatutoryReporting: null,
    minUomIssConvFactor: null,
    maxUomIssConvFactor: null,
    minUomUqcConvFactor: null,
    maxUomUqcConvFactor: null,
    minShelfLifeMonths: null,
    maxShelfLifeMonths: null,
    minShelfLifeDays: null,
    maxShelfLifeDays: null,
    minStdRate: null,
    maxStdRate: null,
    minLeadTimeDays: null,
    maxLeadTimeDays: null,
    minStdLossOnDry: null,
    maxStdLossOnDry: null,
    minSafetyStock: null,
    maxSafetyStock: null,
    minEconomicOrderQty: null,
    maxEconomicOrderQty: null,
    minDesiredPackSize: null,
    maxDesiredPackSize: null,
    minAllowedAllergenPercent: null,
    maxAllowedAllergenPercent: null,
    minStdMfgFeesPerUnit: null,
    maxStdMfgFeesPerUnit: null,
    minConversionFactor: null,
    maxConversionFactor: null,
    createdFrom: '',
    createdTo: '',
    updatedFrom: '',
    updatedTo: '',
    sortBy: 'itemName',
    sortDescending: false,
    pageNumber: 1,
    pageSize: 20,
    currentBuyer: '',
    mainProdCentre: '',
    freightOn: '',
  };
};

export const buildItemMasterFilter = (params: any): ItemMasterFilter => {
  return {
    search: params.search || undefined,
    itemCode: params.itemCode || undefined,
    itemName: params.itemName || undefined,
    shortName: params.shortName || undefined,
    revNo: params.revNo || undefined,
    itemTypeId: params.itemTypeId || undefined,
    subType: params.subType || undefined,
    gsInd: params.gsInd || undefined,
    goodsType: params.goodsType || undefined,
    pharmacopoeiaName: params.pharmacopoeiaName || undefined,
    unitOfMeasure: params.unitOfMeasure || undefined,
    issuingUnit: params.issuingUnit || undefined,
    drawingRef: params.drawingRef || undefined,
    stdAssayStrength: params.stdAssayStrength || undefined,
    productType: params.productType || undefined,
    salesDivision: params.salesDivision || undefined,
    productGroup: params.productGroup || undefined,
    vendorPartNo: params.vendorPartNo || undefined,
    allergen: params.allergen || undefined,
    activeIngredient: params.activeIngredient || undefined,
    packingFreightInsuranceServices: params.packingFreightInsuranceServices || undefined,
    boughtOut: params.boughtOut || undefined,
    jobWork: params.jobWork || undefined,
    imported: params.imported || undefined,
    taxCreditApplicable: params.taxCreditApplicable || undefined,
    manufactured: params.manufactured || undefined,
    sold: params.sold || undefined,
    keyProduct: params.keyProduct || undefined,
    exported: params.exported || undefined,
    batchNotApplicable: params.batchNotApplicable || undefined,
    qcRequired: params.qcRequired || undefined,
    mfgDateApplicable: params.mfgDateApplicable || undefined,
    expiryDateApplicable: params.expiryDateApplicable || undefined,
    trackSerialNos: params.trackSerialNos || undefined,
    mfgLocNameRequired: params.mfgLocNameRequired || undefined,
    mfgMmYyyyApplicable: params.mfgMmYyyyApplicable || undefined,
    expiryMmYyyyApplicable: params.expiryMmYyyyApplicable || undefined,
    principalForStatutoryReporting: params.principalForStatutoryReporting || undefined,
    minUomIssConvFactor: params.minUomIssConvFactor || undefined,
    maxUomIssConvFactor: params.maxUomIssConvFactor || undefined,
    minUomUqcConvFactor: params.minUomUqcConvFactor || undefined,
    maxUomUqcConvFactor: params.maxUomUqcConvFactor || undefined,
    minShelfLifeMonths: params.minShelfLifeMonths || undefined,
    maxShelfLifeMonths: params.maxShelfLifeMonths || undefined,
    minShelfLifeDays: params.minShelfLifeDays || undefined,
    maxShelfLifeDays: params.maxShelfLifeDays || undefined,
    minStdRate: params.minStdRate || undefined,
    maxStdRate: params.maxStdRate || undefined,
    minLeadTimeDays: params.minLeadTimeDays || undefined,
    maxLeadTimeDays: params.maxLeadTimeDays || undefined,
    minStdLossOnDry: params.minStdLossOnDry || undefined,
    maxStdLossOnDry: params.maxStdLossOnDry || undefined,
    minSafetyStock: params.minSafetyStock || undefined,
    maxSafetyStock: params.maxSafetyStock || undefined,
    minEconomicOrderQty: params.minEconomicOrderQty || undefined,
    maxEconomicOrderQty: params.maxEconomicOrderQty || undefined,
    minDesiredPackSize: params.minDesiredPackSize || undefined,
    maxDesiredPackSize: params.maxDesiredPackSize || undefined,
    minAllowedAllergenPercent: params.minAllowedAllergenPercent || undefined,
    maxAllowedAllergenPercent: params.maxAllowedAllergenPercent || undefined,
    minStdMfgFeesPerUnit: params.minStdMfgFeesPerUnit || undefined,
    maxStdMfgFeesPerUnit: params.maxStdMfgFeesPerUnit || undefined,
    minConversionFactor: params.minConversionFactor || undefined,
    maxConversionFactor: params.maxConversionFactor || undefined,
    createdFrom: params.createdFrom || undefined,
    createdTo: params.createdTo || undefined,
    updatedFrom: params.updatedFrom || undefined,
    updatedTo: params.updatedTo || undefined,
    sortBy: params.sortBy || 'itemName',
    sortDescending: params.sortDescending || false,
    pageNumber: params.pageNumber || 1,
    pageSize: params.pageSize || 20,
    currentBuyer: params.currentBuyer || undefined,
    mainProdCentre: params.mainProdCentre || undefined,
    freightOn: params.freightOn || undefined,
  };
};