import z from "zod"

export const organizationFormSchema = z.object({
  code: z.string().min(1, "Organization code is required").max(10),
  name: z.string().min(1, "Organization name is required").max(100),
  locationTypeId: z.coerce.number().min(1, "Location type is required"),
  contactPerson: z.string().max(100).optional(),
  address1: z.string().max(100).optional(),
  address2: z.string().max(100).optional(),
  city: z.string().max(50).optional(),
  state: z.string().max(50).optional(),
  country: z.string().max(50).optional(),
  zip: z.string().max(10).optional(),
  phone: z.string().max(15).optional(),
  email: z.string().email("Invalid email format").optional().or(z.literal("")),
  website: z.string().url("Invalid website URL").optional().or(z.literal("")),
  gstinNumber: z.string().max(50).optional(),
  tdsCycle: z.string().max(50).optional(),
  employmentStatusCode: z.string().max(50).optional(),
  esiOfficeCode: z.string().max(50).optional(),
  excReginCode: z.string().max(50).optional(),
  stRegnCode: z.string().max(50).optional(),
  cinNumber: z.string().max(50).optional(),
  interfaceCode: z.string().max(50).optional(),
  licenseNumber: z.string().max(50).optional(),
  eccNumber: z.string().max(50).optional(),
  range: z.string().max(50).optional(),
  division: z.string().max(50).optional(),
  collectorate: z.string().max(50).optional(),
  drugLicenseNumber1: z.string().max(50).optional(),
  drugLicenseNumber2: z.string().max(50).optional(),
  foodLicenseNumber: z.string().max(50).optional(),
  cstRegnNumber: z.string().max(50).optional(),
  vatTinNumber: z.string().max(50).optional(),
  panNumber: z.string().max(10).optional(),
  isActive: z.boolean().optional(),
})

export type OrganizationFormValues = z.infer<typeof organizationFormSchema> 