import z from "zod"

export const salesOrderSchema = z.object({
  soNumber: z.string().min(1, "SO Number is required"),
  soDate: z.string().optional(),
  soStatus: z.string().min(1, "Status is required"),
  organizationId: z.number().optional(),
  customerId: z.number().min(1, "Customer is required"),
  paymentTerm: z.string().optional(),
  quotationDate: z.string().optional(),
  quotationNo: z.string().optional(),
  hsnCode: z.string().optional(),
  itemId: z.number().optional(),
  dosageName: z.string().optional(),
  divisionId: z.number().optional(),
  designUnder: z.string().optional(),
  packingStyleDescription: z.string().optional(),
  composition: z.string().optional(),
  packShort: z.string().optional(),
  tabletType: z.string().optional(),
  tabletSize: z.string().optional(),
  changePart: z.string().optional(),
  capsuleSize: z.string().optional(),
  shipperSize: z.string().optional(),
  qtyPerShipper: z.string().optional(),
  noOfShipper: z.string().optional(),
  flavour: z.string().optional(),
  fragrance: z.string().optional(),
  quantity: z.string().optional(),
  focQty: z.string().optional(),
  mrp: z.string().optional(),
  billingRate: z.string().optional(),
  costing: z.string().optional(),
  inventoryCharges: z.string().optional(),
  cylinderCharge: z.string().optional(),
  plateCharges: z.string().optional(),
  domino: z.string().optional(),
  stereo: z.string().optional(),
  shipperDrawingRefCode: z.string().optional(),
  ctnOuterDrawingRefNo: z.string().optional(),
  ctnInnerDrawingRefNo: z.string().optional(),
  foilDrawingRefNo: z.string().optional(),
  leafletDrawingRefNo: z.string().optional(),
  tubeDrawingRefNo: z.string().optional(),
  labelDrawingRefNo: z.string().optional(),
  pmOuterCtnStock: z.string().optional(),
  pmInnerCtnStock: z.string().optional(),
  pmFoilStock: z.string().optional(),
  pmLeafletStock: z.string().optional(),
  pmTubeStock: z.string().optional(),
  pmLabelStock: z.string().optional(),
  drugApprovalUnder: z.string().optional(),
  currentStatus: z.string().optional(),
  comments: z.string().optional(),
  assignedDesigner: z.number().optional(),
  plantEmailSent: z.boolean().optional(),
  isSubmitted: z.boolean().optional(),
  productCode: z.string().optional(),
  country: z.string().optional(),
  customerGstNo: z.string().optional(),
});

export type SalesOrderFormValues = z.infer<typeof salesOrderSchema>

export const salesOrderUpdateSchema = salesOrderSchema.partial();

export type SalesOrderUpdateFormValues = z.infer<typeof salesOrderUpdateSchema>;