INSERT INTO mst_privileges (privileges_id,privilege_name) VALUES 
 (1,'Email Templates'),
 (3,'Manage CMS'),
 (4,'Contact Us Section'),
 (5,'User Section'),
 (6,'Newsletter Section'),
 (7,'FAQ Section'),
 (8,'Interests Section'),
 (1,'Email Templates'),
 (3,'Manage CMS'),
 (4,'Contact Us Section'),
 (5,'User Section'),
 (6,'Newsletter Section'),
 (7,'FAQ Section'),
 (8,'Interests Section'),
 (1,'Email Templates'),
 (3,'Manage CMS'),
 (4,'Contact Us Section'),
 (5,'User Section'),
 (6,'Newsletter Section'),
 (7,'FAQ Section'),
 (8,'Interests Section');