INSERT INTO tbl_cpartmachinename (srno,cpart,mname1,mname2,mname3,mname4) VALUES 
 (1,'A01','Alu Alu New ','Alu Alu Old','Alu Alu Edwin','Alu Alu New Plant'),
 (2,'A10','Alu Alu Edwin','','',''),
 (3,'A11','Alu Alu Edwin','','',''),
 (4,'A12','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (5,'A14','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (6,'A15','Alu Alu New ','Alu Alu Old','Alu Alu Edwin','Alu Alu New Plant'),
 (7,'A02','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (8,'A03','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (9,'A04','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (10,'A05','Alu Alu New ','Alu Alu Old','Alu Alu Edwin','Alu Alu New Plant'),
 (11,'A06','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (12,'A07','Alu Alu New ','Alu Alu Old','','Alu Alu New Plant'),
 (13,'A08','Alu Alu Edwin','','',''),
 (14,'A09','Alu Alu Edwin','','',''),
 (15,'B01','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (16,'B10','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (17,'B11','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (18,'B12','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (19,'B13','Blister Machine New','Blister Machine (G/F)','',''),
 (20,'B14','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (21,'B15','Blister Machine New','Blister Machine Old','',''),
 (22,'B16','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (23,'B18','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (24,'B19','Blister Machine New','Blister Machine Old','',''),
 (25,'B02','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (26,'B20','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (27,'B21','Blister Machine (G/F)','NA','',''),
 (28,'B22','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (29,'B23','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (30,'B24','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (31,'B25','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (32,'B26','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (33,'B28','Blister Machine New','Blister Machine Old','',''),
 (34,'B29','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (35,'B03','Blister Machine (G/F)','','',''),
 (36,'B30','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (37,'B31','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (38,'B32','Blister Machine Old','Blister Machine New','',''),
 (39,'B33','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (40,'B34','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (41,'B35','Blister Machine New','Blister Machine Old','',''),
 (42,'B36','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (43,'B37','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (44,'B38','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (45,'B39','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (46,'B04','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (47,'B40','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (48,'B41','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (49,'B42','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (50,'B43','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (51,'B44','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (52,'B45','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (53,'B46','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (54,'B47','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (55,'B48','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (56,'B49','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (57,'B05','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (58,'B50','Blister Machine (G/F)','Blister Machine New','Blister Machine Old',''),
 (59,'B51','Blister Machine New','Blister Machine Old','',''),
 (60,'B06','Blister Machine New','Blister Machine Old','Blister Machine (G/F)',''),
 (61,'B07','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (62,'B08','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (63,'B09','Blister Machine Old','Blister Machine New','Blister Machine (G/F)',''),
 (64,'S01','ALUMINIUM STRIP Machine','','',''),
 (65,'S10','ALUMINIUM STRIP Machine','','',''),
 (66,'S11','ALUMINIUM STRIP Machine','','',''),
 (67,'S12','ALUMINIUM STRIP Machine','','',''),
 (68,'S13','ALUMINIUM STRIP Machine','','',''),
 (69,'S14','ALUMINIUM STRIP Machine','','',''),
 (70,'S15','ALUMINIUM STRIP Machine','','',''),
 (71,'S17','ALUMINIUM STRIP Machine','','',''),
 (72,'S18','ALUMINIUM STRIP Machine','','',''),
 (73,'S19','ALUMINIUM STRIP Machine','','',''),
 (74,'S02','ALUMINIUM STRIP Machine','','',''),
 (75,'S20','ALUMINIUM STRIP Machine','','',''),
 (76,'S21','ALUMINIUM STRIP Machine','','',''),
 (77,'S22','ALUMINIUM STRIP Machine','','',''),
 (78,'S23','ALUMINIUM STRIP Machine','','',''),
 (79,'S03','ALUMINIUM STRIP Machine','','',''),
 (80,'S04','ALUMINIUM STRIP Machine','','',''),
 (81,'S05','ALUMINIUM STRIP Machine','','',''),
 (82,'S06','ALUMINIUM STRIP Machine','','',''),
 (83,'S07','ALUMINIUM STRIP Machine','','',''),
 (84,'S08','ALUMINIUM STRIP Machine','','',''),
 (85,'S09','ALUMINIUM STRIP Machine','','','');