INSERT INTO tbl_machine_master (machine_id,machine_name,machine_type,machine_capacity,machine_status,is_deleted,machine_image) VALUES 
 (41,'Sachet Filling','Oinment/Filling',NULL,'Final Packing',0,NULL),
 (42,'Tube Filling','Oinment/Filling',NULL,'Final Packing',0,NULL),
 (36,'20 stn.(CIP/G.floor)','Tablet/Compression',NULL,'Compression',0,NULL),
 (37,'Coating pan 36(Ist)','Tablet/Coating',NULL,'Coating',0,NULL),
 (38,'Coating pan 36(IInd.)','Tablet/Coating',NULL,'Coating',0,NULL),
 (39,'Coating pan 48','Tablet/Coating',NULL,'Coating',0,NULL),
 (40,'Auto Coater','Tablet/Coating',NULL,'Coating',0,NULL),
 (34,'37 stn.(Chamunda)','Tablet/Compression',NULL,'Compression',0,NULL),
 (35,'45 stn.(Chamunda)','Tablet/Compression',NULL,'Compression',0,NULL),
 (33,'27 stn.(CIP/G .floor)','Tablet/Compression',NULL,'Compression',0,NULL),
 (27,'60','Tablet/Granulation',NULL,'Granulation',0,NULL),
 (28,'120','Tablet/Granulation',NULL,'Granulation',0,NULL),
 (29,'120 - 2 ','Tablet/Granulation',NULL,'Granulation',0,NULL),
 (30,'CAPSULE FILLING','Capsule/Filling',NULL,'Capsule Filling',0,NULL),
 (31,'27 stn.(Accura)','Tablet/Compression',NULL,'Compression',0,NULL),
 (32,'27 stn.(Cadmach)','Tablet/Compression',NULL,'Compression',0,NULL),
 (43,'Alu Alu New','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (44,'Alu Alu Old','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (45,'Alu Alu New Plant','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (46,'Alu Alu Edwin','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (47,'Blister Machine Old','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (48,'Blister Machine New','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (49,'Blister Machine (G/F)','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (50,'Aluminium Strip Machine','Tablet/Packing',NULL,'Final Packing',0,NULL),
 (51,'Bottle Filling','Oinment/Filling',NULL,'Final Packing',0,NULL),
 (52,'Liquid Filling','Liquid/Filling-Sealing',NULL,'',0,NULL),
 (53,'Suger Melting Vessal(750 ltr)','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (54,'Syrup Manufacturing Vessel(1000 ltr)','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (55,'Storage Vessel(1000 ltr)','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (56,'Manufacturing Vessel(100 ltr)','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (57,'Powder Transfer Vessel','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (58,'Filter Press(8 x8 Plates)(500 ltr/hrs)','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (59,'Filter Press (14 x 10 Plates)','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (60,'Inline Homogenizer','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (61,'Sugar Transfer Pump','Liquid/Manufacturing',NULL,NULL,0,NULL),
 (62,'Bottle Washing Machine (1920 to 3840 BPH)','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (63,'Water Storage Tank-1 (75 Ltr)','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (64,'Water Storage Tank-2 (75 Ltr)','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (65,'Turn Table','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (66,'Pre Inspection with Magnify (2400 to 4800)','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (67,'Automatic 4 H Volumetric Liquid Filling Machine','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (68,'Float Tank (150 ltr)','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (69,'Automatic 4 H ROPP Cap Sealing Machine','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (70,'Online Bottle Inspection Machine','Liquid/Filling-Sealing',NULL,NULL,0,NULL),
 (71,'Automatic Self Adhesive Vertical Labeling Machine','Liquid/Packing',NULL,NULL,0,NULL),
 (72,'Five Line Thermal Ink Jet Printer','Liquid/Packing',NULL,NULL,0,NULL),
 (73,'Packing Conveyor Belt 9 Width','Liquid/Packing',NULL,NULL,0,NULL),
 (74,'Water Phase Vessel (150 ltr)','Oinment/Manufacturing',NULL,NULL,0,NULL),
 (75,'Wax Phase Vessel (150 ltr)','Oinment/Manufacturing',NULL,NULL,0,NULL),
 (76,'Manufacturing Vessel (250 ltr)','Oinment/Manufacturing',NULL,NULL,0,NULL),
 (77,'Digital Balance (300 kg)','Oinment/Manufacturing',NULL,NULL,0,NULL),
 (78,'Storage Tank No. 1 (200 ltr)','Oinment/Manufacturing',NULL,NULL,0,NULL),
 (79,'Storage Tank No. 2 (200 ltr)','Oinment/Filling',NULL,NULL,0,NULL),
 (80,'Storage Tank No. 3  (300 ltr)','Oinment/Filling',NULL,NULL,0,NULL),
 (81,'Tube Filling M/C ','Oinment/Filling',NULL,NULL,0,NULL),
 (82,'Digital Balance (300 gm)','Oinment/Filling',NULL,NULL,0,NULL),
 (83,'Conveyor Belt','Oinment/Packing',NULL,NULL,0,NULL),
 (84,'Dispensing Booth','SoftGel/Dispensing',NULL,NULL,0,NULL),
 (85,'Planetry Mixer Machine','SoftGel/Medicament-Mfg',NULL,NULL,0,NULL),
 (86,'Gelatin Meltor Rector','SoftGel/Gelatin-Mass1',NULL,NULL,0,NULL),
 (87,'Encapsulation machine with Tumbler (Bhochang)','SoftGel/Encapsulation',NULL,NULL,0,NULL),
 (88,'Trolley With Tray','SoftGel/Drying',NULL,NULL,0,NULL),
 (89,'Insepction Table','SoftGel/Inspection',NULL,NULL,0,NULL),
 (90,'Polishing Pan','SoftGel/Polishing',NULL,NULL,0,NULL),
 (91,'Blister Machine With Conveyor Belt)','SoftGel/Primary-Packing',NULL,NULL,0,NULL),
 (92,'Manual Person','SoftGel/Secondory-Packing',NULL,NULL,0,NULL);